// Code generated by cfgx. DO NOT EDIT.

package config

import (
	"os"
	"strconv"
)

type databaseConfig struct{}

type indexingConfig struct{}

type qdrantConfig struct{}

type serverConfig struct{}

func (databaseConfig) Dsn() string {
	if v := os.Getenv("CONFIG_DATABASE_DSN"); v != "" {
		return v
	}
	return "postgres://semantix:semantix@localhost:5432/semantix?sslmode=disable"
}

func (indexingConfig) CloneDir() string {
	if v := os.Getenv("CONFIG_INDEXING_CLONE_DIR"); v != "" {
		return v
	}
	return "./tmp/repos"
}

func (indexingConfig) MaxConcurrentJobs() int64 {
	if v := os.Getenv("CONFIG_INDEXING_MAX_CONCURRENT_JOBS"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 2
}

func (indexingConfig) MaxFileSizeBytes() int64 {
	if v := os.Getenv("CONFIG_INDEXING_MAX_FILE_SIZE_BYTES"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 1048576
}

func (qdrantConfig) Address() string {
	if v := os.Getenv("CONFIG_QDRANT_ADDRESS"); v != "" {
		return v
	}
	return "localhost:6334"
}

func (qdrantConfig) CollectionName() string {
	if v := os.Getenv("CONFIG_QDRANT_COLLECTION_NAME"); v != "" {
		return v
	}
	return "semantix_chunks"
}

func (serverConfig) CorsAllowedOrigins() []string {
	if v := os.Getenv("CONFIG_SERVER_CORS_ALLOWED_ORIGINS"); v != "" {
		// Array overrides not supported via env vars
	}
	return []string{"http://localhost:3000"}
}

func (serverConfig) Port() int64 {
	if v := os.Getenv("CONFIG_SERVER_PORT"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 3001
}

func Environment() string {
	if v := os.Getenv("CONFIG_ENVIRONMENT"); v != "" {
		return v
	}
	return "development"
}

var (
	Database databaseConfig
	Indexing indexingConfig
	Qdrant   qdrantConfig
	Server   serverConfig
)
