// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilesByRepoID = `-- name: CountFilesByRepoID :one
SELECT COUNT(*)
FROM files
WHERE repo_id = $1
`

func (q *Queries) CountFilesByRepoID(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByRepoID, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    repo_id,
    path,
    shasum,
    language,
    size_bytes,
    chunk_count,
    indexed_at,
    created,
    updated
  )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, repo_id, path, shasum, language, size_bytes, chunk_count, indexed_at, created, updated
`

type CreateFileParams struct {
	RepoID     int64       `json:"repo_id"`
	Path       string      `json:"path"`
	Shasum     string      `json:"shasum"`
	Language   pgtype.Text `json:"language"`
	SizeBytes  int64       `json:"size_bytes"`
	ChunkCount int32       `json:"chunk_count"`
	IndexedAt  pgtype.Int8 `json:"indexed_at"`
	Created    int64       `json:"created"`
	Updated    int64       `json:"updated"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.RepoID,
		arg.Path,
		arg.Shasum,
		arg.Language,
		arg.SizeBytes,
		arg.ChunkCount,
		arg.IndexedAt,
		arg.Created,
		arg.Updated,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.Shasum,
		&i.Language,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.IndexedAt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteFilesByRepoID = `-- name: DeleteFilesByRepoID :exec
DELETE FROM files
WHERE repo_id = $1
`

func (q *Queries) DeleteFilesByRepoID(ctx context.Context, repoID int64) error {
	_, err := q.db.Exec(ctx, deleteFilesByRepoID, repoID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, repo_id, path, shasum, language, size_bytes, chunk_count, indexed_at, created, updated
FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.Shasum,
		&i.Language,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.IndexedAt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getFileByRepoAndPath = `-- name: GetFileByRepoAndPath :one
SELECT id, repo_id, path, shasum, language, size_bytes, chunk_count, indexed_at, created, updated
FROM files
WHERE repo_id = $1
  AND path = $2
`

type GetFileByRepoAndPathParams struct {
	RepoID int64  `json:"repo_id"`
	Path   string `json:"path"`
}

func (q *Queries) GetFileByRepoAndPath(ctx context.Context, arg GetFileByRepoAndPathParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByRepoAndPath, arg.RepoID, arg.Path)
	var i File
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.Shasum,
		&i.Language,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.IndexedAt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getFilesWithDifferentShasum = `-- name: GetFilesWithDifferentShasum :many
SELECT f.id, f.repo_id, f.path, f.shasum, f.language, f.size_bytes, f.chunk_count, f.indexed_at, f.created, f.updated
FROM files f
WHERE f.repo_id = $1
  AND f.shasum != ALL($2::TEXT [])
`

type GetFilesWithDifferentShasumParams struct {
	RepoID  int64    `json:"repo_id"`
	Column2 []string `json:"column_2"`
}

func (q *Queries) GetFilesWithDifferentShasum(ctx context.Context, arg GetFilesWithDifferentShasumParams) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesWithDifferentShasum, arg.RepoID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Path,
			&i.Shasum,
			&i.Language,
			&i.SizeBytes,
			&i.ChunkCount,
			&i.IndexedAt,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByRepoID = `-- name: ListFilesByRepoID :many
SELECT id, repo_id, path, shasum, language, size_bytes, chunk_count, indexed_at, created, updated
FROM files
WHERE repo_id = $1
ORDER BY path ASC
`

func (q *Queries) ListFilesByRepoID(ctx context.Context, repoID int64) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByRepoID, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Path,
			&i.Shasum,
			&i.Language,
			&i.SizeBytes,
			&i.ChunkCount,
			&i.IndexedAt,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumChunksByRepoID = `-- name: SumChunksByRepoID :one
SELECT COALESCE(SUM(chunk_count), 0)::BIGINT AS total_chunks
FROM files
WHERE repo_id = $1
`

func (q *Queries) SumChunksByRepoID(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumChunksByRepoID, repoID)
	var total_chunks int64
	err := row.Scan(&total_chunks)
	return total_chunks, err
}

const updateFileShasum = `-- name: UpdateFileShasum :one
UPDATE files
SET shasum = $2,
  chunk_count = $3,
  indexed_at = $4,
  updated = $5
WHERE id = $1
RETURNING id, repo_id, path, shasum, language, size_bytes, chunk_count, indexed_at, created, updated
`

type UpdateFileShasumParams struct {
	ID         int64       `json:"id"`
	Shasum     string      `json:"shasum"`
	ChunkCount int32       `json:"chunk_count"`
	IndexedAt  pgtype.Int8 `json:"indexed_at"`
	Updated    int64       `json:"updated"`
}

func (q *Queries) UpdateFileShasum(ctx context.Context, arg UpdateFileShasumParams) (File, error) {
	row := q.db.QueryRow(ctx, updateFileShasum,
		arg.ID,
		arg.Shasum,
		arg.ChunkCount,
		arg.IndexedAt,
		arg.Updated,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.Shasum,
		&i.Language,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.IndexedAt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const upsertFile = `-- name: UpsertFile :one
INSERT INTO files (
    repo_id,
    path,
    shasum,
    language,
    size_bytes,
    chunk_count,
    indexed_at,
    created,
    updated
  )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT (repo_id, path) DO
UPDATE
SET shasum = EXCLUDED.shasum,
  language = EXCLUDED.language,
  size_bytes = EXCLUDED.size_bytes,
  chunk_count = EXCLUDED.chunk_count,
  indexed_at = EXCLUDED.indexed_at,
  updated = EXCLUDED.updated
RETURNING id, repo_id, path, shasum, language, size_bytes, chunk_count, indexed_at, created, updated
`

type UpsertFileParams struct {
	RepoID     int64       `json:"repo_id"`
	Path       string      `json:"path"`
	Shasum     string      `json:"shasum"`
	Language   pgtype.Text `json:"language"`
	SizeBytes  int64       `json:"size_bytes"`
	ChunkCount int32       `json:"chunk_count"`
	IndexedAt  pgtype.Int8 `json:"indexed_at"`
	Created    int64       `json:"created"`
	Updated    int64       `json:"updated"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) (File, error) {
	row := q.db.QueryRow(ctx, upsertFile,
		arg.RepoID,
		arg.Path,
		arg.Shasum,
		arg.Language,
		arg.SizeBytes,
		arg.ChunkCount,
		arg.IndexedAt,
		arg.Created,
		arg.Updated,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.Shasum,
		&i.Language,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.IndexedAt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
