// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: git_tokens.sql

package db

import (
	"context"
)

const createGitToken = `-- name: CreateGitToken :one
INSERT INTO git_tokens (
    workspace_id,
    provider,
    name,
    token_encrypted,
    created,
    updated
  )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, provider, name, token_encrypted, created, updated
`

type CreateGitTokenParams struct {
	WorkspaceID    int64  `json:"workspace_id"`
	Provider       string `json:"provider"`
	Name           string `json:"name"`
	TokenEncrypted string `json:"token_encrypted"`
	Created        int64  `json:"created"`
	Updated        int64  `json:"updated"`
}

func (q *Queries) CreateGitToken(ctx context.Context, arg CreateGitTokenParams) (GitToken, error) {
	row := q.db.QueryRow(ctx, createGitToken,
		arg.WorkspaceID,
		arg.Provider,
		arg.Name,
		arg.TokenEncrypted,
		arg.Created,
		arg.Updated,
	)
	var i GitToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Name,
		&i.TokenEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteGitToken = `-- name: DeleteGitToken :exec
DELETE FROM git_tokens
WHERE id = $1
`

func (q *Queries) DeleteGitToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGitToken, id)
	return err
}

const deleteGitTokensByWorkspace = `-- name: DeleteGitTokensByWorkspace :exec
DELETE FROM git_tokens
WHERE workspace_id = $1
`

func (q *Queries) DeleteGitTokensByWorkspace(ctx context.Context, workspaceID int64) error {
	_, err := q.db.Exec(ctx, deleteGitTokensByWorkspace, workspaceID)
	return err
}

const getGitTokenByID = `-- name: GetGitTokenByID :one
SELECT id, workspace_id, provider, name, token_encrypted, created, updated
FROM git_tokens
WHERE id = $1
`

func (q *Queries) GetGitTokenByID(ctx context.Context, id int64) (GitToken, error) {
	row := q.db.QueryRow(ctx, getGitTokenByID, id)
	var i GitToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Name,
		&i.TokenEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listGitTokensByWorkspace = `-- name: ListGitTokensByWorkspace :many
SELECT id, workspace_id, provider, name, token_encrypted, created, updated
FROM git_tokens
WHERE workspace_id = $1
ORDER BY created DESC
`

func (q *Queries) ListGitTokensByWorkspace(ctx context.Context, workspaceID int64) ([]GitToken, error) {
	rows, err := q.db.Query(ctx, listGitTokensByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitToken
	for rows.Next() {
		var i GitToken
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Provider,
			&i.Name,
			&i.TokenEncrypted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitTokensByWorkspaceAndProvider = `-- name: ListGitTokensByWorkspaceAndProvider :many
SELECT id, workspace_id, provider, name, token_encrypted, created, updated
FROM git_tokens
WHERE workspace_id = $1
  AND provider = $2
ORDER BY created DESC
`

type ListGitTokensByWorkspaceAndProviderParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Provider    string `json:"provider"`
}

func (q *Queries) ListGitTokensByWorkspaceAndProvider(ctx context.Context, arg ListGitTokensByWorkspaceAndProviderParams) ([]GitToken, error) {
	rows, err := q.db.Query(ctx, listGitTokensByWorkspaceAndProvider, arg.WorkspaceID, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitToken
	for rows.Next() {
		var i GitToken
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Provider,
			&i.Name,
			&i.TokenEncrypted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGitToken = `-- name: UpdateGitToken :one
UPDATE git_tokens
SET name = $2,
  token_encrypted = $3,
  updated = $4
WHERE id = $1
RETURNING id, workspace_id, provider, name, token_encrypted, created, updated
`

type UpdateGitTokenParams struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	TokenEncrypted string `json:"token_encrypted"`
	Updated        int64  `json:"updated"`
}

func (q *Queries) UpdateGitToken(ctx context.Context, arg UpdateGitTokenParams) (GitToken, error) {
	row := q.db.QueryRow(ctx, updateGitToken,
		arg.ID,
		arg.Name,
		arg.TokenEncrypted,
		arg.Updated,
	)
	var i GitToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Name,
		&i.TokenEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
