// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID         int64       `json:"id"`
	RepoID     int64       `json:"repo_id"`
	Path       string      `json:"path"`
	Shasum     string      `json:"shasum"`
	Language   pgtype.Text `json:"language"`
	SizeBytes  int64       `json:"size_bytes"`
	ChunkCount int32       `json:"chunk_count"`
	IndexedAt  pgtype.Int8 `json:"indexed_at"`
	Created    int64       `json:"created"`
	Updated    int64       `json:"updated"`
}

type GitToken struct {
	ID             int64  `json:"id"`
	WorkspaceID    int64  `json:"workspace_id"`
	Provider       string `json:"provider"`
	Name           string `json:"name"`
	TokenEncrypted string `json:"token_encrypted"`
	Created        int64  `json:"created"`
	Updated        int64  `json:"updated"`
}

type Repo struct {
	ID            int64       `json:"id"`
	WorkspaceID   int64       `json:"workspace_id"`
	GitTokenID    pgtype.Int8 `json:"git_token_id"`
	Url           string      `json:"url"`
	Name          string      `json:"name"`
	Owner         string      `json:"owner"`
	DefaultBranch string      `json:"default_branch"`
	LastCommitSha pgtype.Text `json:"last_commit_sha"`
	Status        string      `json:"status"`
	Error         pgtype.Text `json:"error"`
	Created       int64       `json:"created"`
	Updated       int64       `json:"updated"`
}

type Workspace struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Slug    string `json:"slug"`
	Created int64  `json:"created"`
	Updated int64  `json:"updated"`
}
