// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingRepo = `-- name: ClaimPendingRepo :one
UPDATE repos
SET status = 'indexing',
  updated = $1
WHERE id = (
    SELECT id
    FROM repos
    WHERE status = 'pending'
    ORDER BY created ASC
    LIMIT 1 FOR
    UPDATE SKIP LOCKED
  )
RETURNING id, workspace_id, git_token_id, url, name, owner, default_branch, last_commit_sha, status, error, created, updated
`

func (q *Queries) ClaimPendingRepo(ctx context.Context, updated int64) (Repo, error) {
	row := q.db.QueryRow(ctx, claimPendingRepo, updated)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Name,
		&i.Owner,
		&i.DefaultBranch,
		&i.LastCommitSha,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const countReposByWorkspace = `-- name: CountReposByWorkspace :one
SELECT COUNT(*)
FROM repos
WHERE workspace_id = $1
`

func (q *Queries) CountReposByWorkspace(ctx context.Context, workspaceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReposByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReposByWorkspaceAndStatus = `-- name: CountReposByWorkspaceAndStatus :one
SELECT COUNT(*)
FROM repos
WHERE workspace_id = $1
  AND status = $2
`

type CountReposByWorkspaceAndStatusParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Status      string `json:"status"`
}

func (q *Queries) CountReposByWorkspaceAndStatus(ctx context.Context, arg CountReposByWorkspaceAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReposByWorkspaceAndStatus, arg.WorkspaceID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (
    workspace_id,
    git_token_id,
    url,
    name,
    owner,
    default_branch,
    status,
    created,
    updated
  )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, git_token_id, url, name, owner, default_branch, last_commit_sha, status, error, created, updated
`

type CreateRepoParams struct {
	WorkspaceID   int64       `json:"workspace_id"`
	GitTokenID    pgtype.Int8 `json:"git_token_id"`
	Url           string      `json:"url"`
	Name          string      `json:"name"`
	Owner         string      `json:"owner"`
	DefaultBranch string      `json:"default_branch"`
	Status        string      `json:"status"`
	Created       int64       `json:"created"`
	Updated       int64       `json:"updated"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.WorkspaceID,
		arg.GitTokenID,
		arg.Url,
		arg.Name,
		arg.Owner,
		arg.DefaultBranch,
		arg.Status,
		arg.Created,
		arg.Updated,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Name,
		&i.Owner,
		&i.DefaultBranch,
		&i.LastCommitSha,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos
WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const deleteReposByWorkspace = `-- name: DeleteReposByWorkspace :exec
DELETE FROM repos
WHERE workspace_id = $1
`

func (q *Queries) DeleteReposByWorkspace(ctx context.Context, workspaceID int64) error {
	_, err := q.db.Exec(ctx, deleteReposByWorkspace, workspaceID)
	return err
}

const getPendingRepos = `-- name: GetPendingRepos :many
SELECT id, workspace_id, git_token_id, url, name, owner, default_branch, last_commit_sha, status, error, created, updated
FROM repos
WHERE status = 'pending'
ORDER BY created ASC
LIMIT $1
`

func (q *Queries) GetPendingRepos(ctx context.Context, limit int32) ([]Repo, error) {
	rows, err := q.db.Query(ctx, getPendingRepos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.GitTokenID,
			&i.Url,
			&i.Name,
			&i.Owner,
			&i.DefaultBranch,
			&i.LastCommitSha,
			&i.Status,
			&i.Error,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, workspace_id, git_token_id, url, name, owner, default_branch, last_commit_sha, status, error, created, updated
FROM repos
WHERE id = $1
`

func (q *Queries) GetRepoByID(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Name,
		&i.Owner,
		&i.DefaultBranch,
		&i.LastCommitSha,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getRepoByWorkspaceAndURL = `-- name: GetRepoByWorkspaceAndURL :one
SELECT id, workspace_id, git_token_id, url, name, owner, default_branch, last_commit_sha, status, error, created, updated
FROM repos
WHERE workspace_id = $1
  AND url = $2
`

type GetRepoByWorkspaceAndURLParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Url         string `json:"url"`
}

func (q *Queries) GetRepoByWorkspaceAndURL(ctx context.Context, arg GetRepoByWorkspaceAndURLParams) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByWorkspaceAndURL, arg.WorkspaceID, arg.Url)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Name,
		&i.Owner,
		&i.DefaultBranch,
		&i.LastCommitSha,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listReposByWorkspace = `-- name: ListReposByWorkspace :many
SELECT id, workspace_id, git_token_id, url, name, owner, default_branch, last_commit_sha, status, error, created, updated
FROM repos
WHERE workspace_id = $1
ORDER BY created DESC
LIMIT $2 OFFSET $3
`

type ListReposByWorkspaceParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListReposByWorkspace(ctx context.Context, arg ListReposByWorkspaceParams) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listReposByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.GitTokenID,
			&i.Url,
			&i.Name,
			&i.Owner,
			&i.DefaultBranch,
			&i.LastCommitSha,
			&i.Status,
			&i.Error,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByWorkspaceAndStatus = `-- name: ListReposByWorkspaceAndStatus :many
SELECT id, workspace_id, git_token_id, url, name, owner, default_branch, last_commit_sha, status, error, created, updated
FROM repos
WHERE workspace_id = $1
  AND status = $2
ORDER BY created DESC
LIMIT $3 OFFSET $4
`

type ListReposByWorkspaceAndStatusParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Status      string `json:"status"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListReposByWorkspaceAndStatus(ctx context.Context, arg ListReposByWorkspaceAndStatusParams) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listReposByWorkspaceAndStatus,
		arg.WorkspaceID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.GitTokenID,
			&i.Url,
			&i.Name,
			&i.Owner,
			&i.DefaultBranch,
			&i.LastCommitSha,
			&i.Status,
			&i.Error,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepoAfterClone = `-- name: UpdateRepoAfterClone :one
UPDATE repos
SET last_commit_sha = $2,
  status = $3,
  updated = $4
WHERE id = $1
RETURNING id, workspace_id, git_token_id, url, name, owner, default_branch, last_commit_sha, status, error, created, updated
`

type UpdateRepoAfterCloneParams struct {
	ID            int64       `json:"id"`
	LastCommitSha pgtype.Text `json:"last_commit_sha"`
	Status        string      `json:"status"`
	Updated       int64       `json:"updated"`
}

func (q *Queries) UpdateRepoAfterClone(ctx context.Context, arg UpdateRepoAfterCloneParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepoAfterClone,
		arg.ID,
		arg.LastCommitSha,
		arg.Status,
		arg.Updated,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Name,
		&i.Owner,
		&i.DefaultBranch,
		&i.LastCommitSha,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateRepoGitToken = `-- name: UpdateRepoGitToken :one
UPDATE repos
SET git_token_id = $2,
  updated = $3
WHERE id = $1
RETURNING id, workspace_id, git_token_id, url, name, owner, default_branch, last_commit_sha, status, error, created, updated
`

type UpdateRepoGitTokenParams struct {
	ID         int64       `json:"id"`
	GitTokenID pgtype.Int8 `json:"git_token_id"`
	Updated    int64       `json:"updated"`
}

func (q *Queries) UpdateRepoGitToken(ctx context.Context, arg UpdateRepoGitTokenParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepoGitToken, arg.ID, arg.GitTokenID, arg.Updated)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Name,
		&i.Owner,
		&i.DefaultBranch,
		&i.LastCommitSha,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateRepoStatus = `-- name: UpdateRepoStatus :one
UPDATE repos
SET status = $2,
  error = $3,
  updated = $4
WHERE id = $1
RETURNING id, workspace_id, git_token_id, url, name, owner, default_branch, last_commit_sha, status, error, created, updated
`

type UpdateRepoStatusParams struct {
	ID      int64       `json:"id"`
	Status  string      `json:"status"`
	Error   pgtype.Text `json:"error"`
	Updated int64       `json:"updated"`
}

func (q *Queries) UpdateRepoStatus(ctx context.Context, arg UpdateRepoStatusParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepoStatus,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.Updated,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Name,
		&i.Owner,
		&i.DefaultBranch,
		&i.LastCommitSha,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
