// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token, created, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token, created, expires_at
`

type CreateSessionParams struct {
	UserID    int64       `json:"user_id"`
	Token     string      `json:"token"`
	Created   int64       `json:"created"`
	ExpiresAt pgtype.Int8 `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Token,
		arg.Created,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Created,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, created, updated)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, created, updated
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Created      int64  `json:"created"`
	Updated      int64  `json:"updated"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Created,
		arg.Updated,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.id, s.user_id, s.token, s.created, s.expires_at,
       u.email
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = $1
  AND (s.expires_at IS NULL OR s.expires_at > $2)
`

type GetSessionByTokenParams struct {
	Token string      `json:"token"`
	Now   pgtype.Int8 `json:"now"`
}

type GetSessionByTokenRow struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	Token     string      `json:"token"`
	Created   int64       `json:"created"`
	ExpiresAt pgtype.Int8 `json:"expires_at"`
	Email     string      `json:"email"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, arg.Token, arg.Now)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Created,
		&i.ExpiresAt,
		&i.Email,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created, updated
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
