// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilesByRepo = `-- name: CountFilesByRepo :one
SELECT COUNT(*)
FROM files
WHERE repo_id = $1
`

func (q *Queries) CountFilesByRepo(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByRepo, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (repo_id, path, content_hash, size_bytes, language, indexed_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, repo_id, path, content_hash, size_bytes, language, indexed_at
`

type CreateFileParams struct {
	RepoID      int64       `json:"repo_id"`
	Path        string      `json:"path"`
	ContentHash string      `json:"content_hash"`
	SizeBytes   int64       `json:"size_bytes"`
	Language    pgtype.Text `json:"language"`
	IndexedAt   int64       `json:"indexed_at"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.RepoID,
		arg.Path,
		arg.ContentHash,
		arg.SizeBytes,
		arg.Language,
		arg.IndexedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.ContentHash,
		&i.SizeBytes,
		&i.Language,
		&i.IndexedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteFilesByPaths = `-- name: DeleteFilesByPaths :exec
DELETE FROM files
WHERE repo_id = $1 AND path = ANY($2::text[])
`

type DeleteFilesByPathsParams struct {
	RepoID  int64    `json:"repo_id"`
	Column2 []string `json:"column_2"`
}

func (q *Queries) DeleteFilesByPaths(ctx context.Context, arg DeleteFilesByPathsParams) error {
	_, err := q.db.Exec(ctx, deleteFilesByPaths, arg.RepoID, arg.Column2)
	return err
}

const deleteFilesByRepo = `-- name: DeleteFilesByRepo :exec
DELETE FROM files
WHERE repo_id = $1
`

func (q *Queries) DeleteFilesByRepo(ctx context.Context, repoID int64) error {
	_, err := q.db.Exec(ctx, deleteFilesByRepo, repoID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, repo_id, path, content_hash, size_bytes, language, indexed_at
FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.ContentHash,
		&i.SizeBytes,
		&i.Language,
		&i.IndexedAt,
	)
	return i, err
}

const getFileByRepoAndPath = `-- name: GetFileByRepoAndPath :one
SELECT id, repo_id, path, content_hash, size_bytes, language, indexed_at
FROM files
WHERE repo_id = $1 AND path = $2
`

type GetFileByRepoAndPathParams struct {
	RepoID int64  `json:"repo_id"`
	Path   string `json:"path"`
}

func (q *Queries) GetFileByRepoAndPath(ctx context.Context, arg GetFileByRepoAndPathParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByRepoAndPath, arg.RepoID, arg.Path)
	var i File
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.ContentHash,
		&i.SizeBytes,
		&i.Language,
		&i.IndexedAt,
	)
	return i, err
}

const listFilesByRepo = `-- name: ListFilesByRepo :many
SELECT id, repo_id, path, content_hash, size_bytes, language, indexed_at
FROM files
WHERE repo_id = $1
ORDER BY path ASC
`

func (q *Queries) ListFilesByRepo(ctx context.Context, repoID int64) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Path,
			&i.ContentHash,
			&i.SizeBytes,
			&i.Language,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFile = `-- name: UpsertFile :one
INSERT INTO files (repo_id, path, content_hash, size_bytes, language, indexed_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (repo_id, path) DO UPDATE SET
    content_hash = EXCLUDED.content_hash,
    size_bytes = EXCLUDED.size_bytes,
    language = EXCLUDED.language,
    indexed_at = EXCLUDED.indexed_at
RETURNING id, repo_id, path, content_hash, size_bytes, language, indexed_at
`

type UpsertFileParams struct {
	RepoID      int64       `json:"repo_id"`
	Path        string      `json:"path"`
	ContentHash string      `json:"content_hash"`
	SizeBytes   int64       `json:"size_bytes"`
	Language    pgtype.Text `json:"language"`
	IndexedAt   int64       `json:"indexed_at"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) (File, error) {
	row := q.db.QueryRow(ctx, upsertFile,
		arg.RepoID,
		arg.Path,
		arg.ContentHash,
		arg.SizeBytes,
		arg.Language,
		arg.IndexedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.ContentHash,
		&i.SizeBytes,
		&i.Language,
		&i.IndexedAt,
	)
	return i, err
}
