// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: index_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIndexRun = `-- name: CreateIndexRun :one
INSERT INTO index_runs (repo_id, status, started_at)
VALUES ($1, $2, $3)
RETURNING id, repo_id, status, started_at, completed_at, files_processed, chunks_created, embeddings_generated, embeddings_cached, error_message, duration_ms
`

type CreateIndexRunParams struct {
	RepoID    int64  `json:"repo_id"`
	Status    string `json:"status"`
	StartedAt int64  `json:"started_at"`
}

func (q *Queries) CreateIndexRun(ctx context.Context, arg CreateIndexRunParams) (IndexRun, error) {
	row := q.db.QueryRow(ctx, createIndexRun, arg.RepoID, arg.Status, arg.StartedAt)
	var i IndexRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilesProcessed,
		&i.ChunksCreated,
		&i.EmbeddingsGenerated,
		&i.EmbeddingsCached,
		&i.ErrorMessage,
		&i.DurationMs,
	)
	return i, err
}

const deleteIndexRunsByRepo = `-- name: DeleteIndexRunsByRepo :exec
DELETE FROM index_runs
WHERE repo_id = $1
`

func (q *Queries) DeleteIndexRunsByRepo(ctx context.Context, repoID int64) error {
	_, err := q.db.Exec(ctx, deleteIndexRunsByRepo, repoID)
	return err
}

const failOrphanedIndexRuns = `-- name: FailOrphanedIndexRuns :exec
UPDATE index_runs
SET status = 'failed',
    completed_at = $1,
    error_message = 'interrupted by server restart'
WHERE status = 'running'
`

func (q *Queries) FailOrphanedIndexRuns(ctx context.Context, completedAt pgtype.Int8) error {
	_, err := q.db.Exec(ctx, failOrphanedIndexRuns, completedAt)
	return err
}

const getIndexRunByID = `-- name: GetIndexRunByID :one
SELECT id, repo_id, status, started_at, completed_at, files_processed, chunks_created, embeddings_generated, embeddings_cached, error_message, duration_ms
FROM index_runs
WHERE id = $1
`

func (q *Queries) GetIndexRunByID(ctx context.Context, id int64) (IndexRun, error) {
	row := q.db.QueryRow(ctx, getIndexRunByID, id)
	var i IndexRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilesProcessed,
		&i.ChunksCreated,
		&i.EmbeddingsGenerated,
		&i.EmbeddingsCached,
		&i.ErrorMessage,
		&i.DurationMs,
	)
	return i, err
}

const listIndexRunsByRepo = `-- name: ListIndexRunsByRepo :many
SELECT id, repo_id, status, started_at, completed_at, files_processed, chunks_created, embeddings_generated, embeddings_cached, error_message, duration_ms
FROM index_runs
WHERE repo_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListIndexRunsByRepoParams struct {
	RepoID int64 `json:"repo_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIndexRunsByRepo(ctx context.Context, arg ListIndexRunsByRepoParams) ([]IndexRun, error) {
	rows, err := q.db.Query(ctx, listIndexRunsByRepo, arg.RepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IndexRun
	for rows.Next() {
		var i IndexRun
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilesProcessed,
			&i.ChunksCreated,
			&i.EmbeddingsGenerated,
			&i.EmbeddingsCached,
			&i.ErrorMessage,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndexRunStats = `-- name: UpdateIndexRunStats :one
UPDATE index_runs
SET files_processed = $2,
    chunks_created = $3,
    embeddings_generated = $4,
    embeddings_cached = $5
WHERE id = $1
RETURNING id, repo_id, status, started_at, completed_at, files_processed, chunks_created, embeddings_generated, embeddings_cached, error_message, duration_ms
`

type UpdateIndexRunStatsParams struct {
	ID                  int64 `json:"id"`
	FilesProcessed      int32 `json:"files_processed"`
	ChunksCreated       int32 `json:"chunks_created"`
	EmbeddingsGenerated int32 `json:"embeddings_generated"`
	EmbeddingsCached    int32 `json:"embeddings_cached"`
}

func (q *Queries) UpdateIndexRunStats(ctx context.Context, arg UpdateIndexRunStatsParams) (IndexRun, error) {
	row := q.db.QueryRow(ctx, updateIndexRunStats,
		arg.ID,
		arg.FilesProcessed,
		arg.ChunksCreated,
		arg.EmbeddingsGenerated,
		arg.EmbeddingsCached,
	)
	var i IndexRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilesProcessed,
		&i.ChunksCreated,
		&i.EmbeddingsGenerated,
		&i.EmbeddingsCached,
		&i.ErrorMessage,
		&i.DurationMs,
	)
	return i, err
}

const updateIndexRunStatus = `-- name: UpdateIndexRunStatus :one
UPDATE index_runs
SET status = $2,
    completed_at = $3,
    error_message = $4,
    duration_ms = $5
WHERE id = $1
RETURNING id, repo_id, status, started_at, completed_at, files_processed, chunks_created, embeddings_generated, embeddings_cached, error_message, duration_ms
`

type UpdateIndexRunStatusParams struct {
	ID           int64       `json:"id"`
	Status       string      `json:"status"`
	CompletedAt  pgtype.Int8 `json:"completed_at"`
	ErrorMessage pgtype.Text `json:"error_message"`
	DurationMs   pgtype.Int8 `json:"duration_ms"`
}

func (q *Queries) UpdateIndexRunStatus(ctx context.Context, arg UpdateIndexRunStatusParams) (IndexRun, error) {
	row := q.db.QueryRow(ctx, updateIndexRunStatus,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.DurationMs,
	)
	var i IndexRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilesProcessed,
		&i.ChunksCreated,
		&i.EmbeddingsGenerated,
		&i.EmbeddingsCached,
		&i.ErrorMessage,
		&i.DurationMs,
	)
	return i, err
}
