// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID          int64       `json:"id"`
	RepoID      int64       `json:"repo_id"`
	Path        string      `json:"path"`
	ContentHash string      `json:"content_hash"`
	SizeBytes   int64       `json:"size_bytes"`
	Language    pgtype.Text `json:"language"`
	IndexedAt   int64       `json:"indexed_at"`
}

type GitToken struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Provider       string      `json:"provider"`
	TokenEncrypted []byte      `json:"token_encrypted"`
	TokenHint      pgtype.Text `json:"token_hint"`
	Created        int64       `json:"created"`
}

type IndexRun struct {
	ID                  int64       `json:"id"`
	RepoID              int64       `json:"repo_id"`
	Status              string      `json:"status"`
	StartedAt           int64       `json:"started_at"`
	CompletedAt         pgtype.Int8 `json:"completed_at"`
	FilesProcessed      int32       `json:"files_processed"`
	ChunksCreated       int32       `json:"chunks_created"`
	EmbeddingsGenerated int32       `json:"embeddings_generated"`
	EmbeddingsCached    int32       `json:"embeddings_cached"`
	ErrorMessage        pgtype.Text `json:"error_message"`
	DurationMs          pgtype.Int8 `json:"duration_ms"`
}

type Repo struct {
	ID           int64       `json:"id"`
	WorkspaceID  int64       `json:"workspace_id"`
	Url          string      `json:"url"`
	Branch       string      `json:"branch"`
	Status       string      `json:"status"`
	IndexedAt    pgtype.Int8 `json:"indexed_at"`
	ErrorMessage pgtype.Text `json:"error_message"`
	Created      int64       `json:"created"`
	Updated      int64       `json:"updated"`
}

type Session struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	Token     string      `json:"token"`
	Created   int64       `json:"created"`
	ExpiresAt pgtype.Int8 `json:"expires_at"`
}

type User struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Created      int64  `json:"created"`
	Updated      int64  `json:"updated"`
}

type Workspace struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Settings    []byte      `json:"settings"`
	Created     int64       `json:"created"`
	Updated     int64       `json:"updated"`
}
