// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID          int64       `json:"id"`
	RepoID      int64       `json:"repo_id"`
	Path        string      `json:"path"`
	ContentHash string      `json:"content_hash"`
	SizeBytes   int64       `json:"size_bytes"`
	Language    pgtype.Text `json:"language"`
	IndexedAt   int64       `json:"indexed_at"`
}

type GitToken struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Provider       string      `json:"provider"`
	TokenEncrypted []byte      `json:"token_encrypted"`
	TokenHint      pgtype.Text `json:"token_hint"`
	Created        int64       `json:"created"`
}

type Repo struct {
	ID           int64       `json:"id"`
	WorkspaceID  int64       `json:"workspace_id"`
	Url          string      `json:"url"`
	Branch       string      `json:"branch"`
	Status       string      `json:"status"`
	IndexedAt    pgtype.Int8 `json:"indexed_at"`
	ErrorMessage pgtype.Text `json:"error_message"`
	Created      int64       `json:"created"`
	Updated      int64       `json:"updated"`
}

type Workspace struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Settings    []byte      `json:"settings"`
	Created     int64       `json:"created"`
	Updated     int64       `json:"updated"`
}
