// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountFilesByRepo(ctx context.Context, repoID int64) (int64, error)
	CountReposByWorkspace(ctx context.Context, workspaceID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkspaces(ctx context.Context) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateGitToken(ctx context.Context, arg CreateGitTokenParams) (GitToken, error)
	CreateIndexRun(ctx context.Context, arg CreateIndexRunParams) (IndexRun, error)
	CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteFile(ctx context.Context, id int64) error
	DeleteFilesByPaths(ctx context.Context, arg DeleteFilesByPathsParams) error
	DeleteFilesByRepo(ctx context.Context, repoID int64) error
	DeleteGitToken(ctx context.Context, id int64) error
	DeleteIndexRunsByRepo(ctx context.Context, repoID int64) error
	DeleteRepo(ctx context.Context, id int64) error
	DeleteReposByWorkspace(ctx context.Context, workspaceID int64) error
	DeleteSession(ctx context.Context, token string) error
	DeleteWorkspace(ctx context.Context, id int64) error
	GetFileByID(ctx context.Context, id int64) (File, error)
	GetFileByRepoAndPath(ctx context.Context, arg GetFileByRepoAndPathParams) (File, error)
	GetGitTokenByID(ctx context.Context, id int64) (GitToken, error)
	GetIndexRunByID(ctx context.Context, id int64) (IndexRun, error)
	GetRepoByID(ctx context.Context, id int64) (Repo, error)
	GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (GetSessionByTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error)
	ListFilesByRepo(ctx context.Context, repoID int64) ([]File, error)
	ListGitTokens(ctx context.Context) ([]GitToken, error)
	ListGitTokensByProvider(ctx context.Context, provider string) ([]GitToken, error)
	ListIndexRunsByRepo(ctx context.Context, arg ListIndexRunsByRepoParams) ([]IndexRun, error)
	ListReposByStatus(ctx context.Context, arg ListReposByStatusParams) ([]Repo, error)
	ListReposByWorkspace(ctx context.Context, arg ListReposByWorkspaceParams) ([]Repo, error)
	ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]Workspace, error)
	UpdateIndexRunStats(ctx context.Context, arg UpdateIndexRunStatsParams) (IndexRun, error)
	UpdateIndexRunStatus(ctx context.Context, arg UpdateIndexRunStatusParams) (IndexRun, error)
	UpdateRepo(ctx context.Context, arg UpdateRepoParams) (Repo, error)
	UpdateRepoStatus(ctx context.Context, arg UpdateRepoStatusParams) (Repo, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpsertFile(ctx context.Context, arg UpsertFileParams) (File, error)
}

var _ Querier = (*Queries)(nil)
