// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountFilesByRepo(ctx context.Context, repoID int64) (int64, error)
	CountReposByWorkspace(ctx context.Context, workspaceID int64) (int64, error)
	CountWorkspaces(ctx context.Context) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateGitToken(ctx context.Context, arg CreateGitTokenParams) (CreateGitTokenRow, error)
	CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteFile(ctx context.Context, id int64) error
	DeleteFilesByPaths(ctx context.Context, arg DeleteFilesByPathsParams) error
	DeleteFilesByRepo(ctx context.Context, repoID int64) error
	DeleteGitToken(ctx context.Context, id int64) error
	DeleteRepo(ctx context.Context, id int64) error
	DeleteReposByWorkspace(ctx context.Context, workspaceID int64) error
	DeleteWorkspace(ctx context.Context, id int64) error
	GetFileByID(ctx context.Context, id int64) (File, error)
	GetFileByRepoAndPath(ctx context.Context, arg GetFileByRepoAndPathParams) (File, error)
	GetGitTokenByID(ctx context.Context, id int64) (GetGitTokenByIDRow, error)
	GetRepoByID(ctx context.Context, id int64) (Repo, error)
	GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	ListFilesByRepo(ctx context.Context, repoID int64) ([]File, error)
	ListGitTokens(ctx context.Context) ([]ListGitTokensRow, error)
	ListGitTokensByProvider(ctx context.Context, provider string) ([]ListGitTokensByProviderRow, error)
	ListReposByStatus(ctx context.Context, arg ListReposByStatusParams) ([]Repo, error)
	ListReposByWorkspace(ctx context.Context, arg ListReposByWorkspaceParams) ([]Repo, error)
	ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]Workspace, error)
	UpdateRepo(ctx context.Context, arg UpdateRepoParams) (Repo, error)
	UpdateRepoStatus(ctx context.Context, arg UpdateRepoStatusParams) (Repo, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpsertFile(ctx context.Context, arg UpsertFileParams) (File, error)
}

var _ Querier = (*Queries)(nil)
