// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReposByGitToken = `-- name: CountReposByGitToken :one
SELECT COUNT(*)
FROM repos
WHERE git_token_id = $1
`

func (q *Queries) CountReposByGitToken(ctx context.Context, gitTokenID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countReposByGitToken, gitTokenID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReposByWorkspace = `-- name: CountReposByWorkspace :one
SELECT COUNT(*)
FROM repos
WHERE workspace_id = $1
`

func (q *Queries) CountReposByWorkspace(ctx context.Context, workspaceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReposByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (workspace_id, git_token_id, url, branch, is_private, status, indexed_at, error_message, created, updated)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workspace_id, git_token_id, url, branch, is_private, status, indexed_at, error_message, created, updated
`

type CreateRepoParams struct {
	WorkspaceID  int64       `json:"workspace_id"`
	GitTokenID   pgtype.Int8 `json:"git_token_id"`
	Url          string      `json:"url"`
	Branch       string      `json:"branch"`
	IsPrivate    bool        `json:"is_private"`
	Status       string      `json:"status"`
	IndexedAt    pgtype.Int8 `json:"indexed_at"`
	ErrorMessage pgtype.Text `json:"error_message"`
	Created      int64       `json:"created"`
	Updated      int64       `json:"updated"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.WorkspaceID,
		arg.GitTokenID,
		arg.Url,
		arg.Branch,
		arg.IsPrivate,
		arg.Status,
		arg.IndexedAt,
		arg.ErrorMessage,
		arg.Created,
		arg.Updated,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Branch,
		&i.IsPrivate,
		&i.Status,
		&i.IndexedAt,
		&i.ErrorMessage,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos
WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const deleteReposByWorkspace = `-- name: DeleteReposByWorkspace :exec
DELETE FROM repos
WHERE workspace_id = $1
`

func (q *Queries) DeleteReposByWorkspace(ctx context.Context, workspaceID int64) error {
	_, err := q.db.Exec(ctx, deleteReposByWorkspace, workspaceID)
	return err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, workspace_id, git_token_id, url, branch, is_private, status, indexed_at, error_message, created, updated
FROM repos
WHERE id = $1
`

func (q *Queries) GetRepoByID(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Branch,
		&i.IsPrivate,
		&i.Status,
		&i.IndexedAt,
		&i.ErrorMessage,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listReposByStatus = `-- name: ListReposByStatus :many
SELECT id, workspace_id, git_token_id, url, branch, is_private, status, indexed_at, error_message, created, updated
FROM repos
WHERE status = $1
ORDER BY created ASC
LIMIT $2
`

type ListReposByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListReposByStatus(ctx context.Context, arg ListReposByStatusParams) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listReposByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.GitTokenID,
			&i.Url,
			&i.Branch,
			&i.IsPrivate,
			&i.Status,
			&i.IndexedAt,
			&i.ErrorMessage,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByWorkspace = `-- name: ListReposByWorkspace :many
SELECT id, workspace_id, git_token_id, url, branch, is_private, status, indexed_at, error_message, created, updated
FROM repos
WHERE workspace_id = $1
ORDER BY created DESC
LIMIT $2 OFFSET $3
`

type ListReposByWorkspaceParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListReposByWorkspace(ctx context.Context, arg ListReposByWorkspaceParams) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listReposByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.GitTokenID,
			&i.Url,
			&i.Branch,
			&i.IsPrivate,
			&i.Status,
			&i.IndexedAt,
			&i.ErrorMessage,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStaleRepos = `-- name: ResetStaleRepos :exec
UPDATE repos
SET status = 'pending',
    updated = $1
WHERE status IN ('cloning', 'indexing')
`

func (q *Queries) ResetStaleRepos(ctx context.Context, updated int64) error {
	_, err := q.db.Exec(ctx, resetStaleRepos, updated)
	return err
}

const updateRepo = `-- name: UpdateRepo :one
UPDATE repos
SET git_token_id = $2,
    url = $3,
    branch = $4,
    is_private = $5,
    updated = $6
WHERE id = $1
RETURNING id, workspace_id, git_token_id, url, branch, is_private, status, indexed_at, error_message, created, updated
`

type UpdateRepoParams struct {
	ID         int64       `json:"id"`
	GitTokenID pgtype.Int8 `json:"git_token_id"`
	Url        string      `json:"url"`
	Branch     string      `json:"branch"`
	IsPrivate  bool        `json:"is_private"`
	Updated    int64       `json:"updated"`
}

func (q *Queries) UpdateRepo(ctx context.Context, arg UpdateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepo,
		arg.ID,
		arg.GitTokenID,
		arg.Url,
		arg.Branch,
		arg.IsPrivate,
		arg.Updated,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Branch,
		&i.IsPrivate,
		&i.Status,
		&i.IndexedAt,
		&i.ErrorMessage,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateRepoStatus = `-- name: UpdateRepoStatus :one
UPDATE repos
SET status = $2,
    indexed_at = $3,
    error_message = $4,
    updated = $5
WHERE id = $1
RETURNING id, workspace_id, git_token_id, url, branch, is_private, status, indexed_at, error_message, created, updated
`

type UpdateRepoStatusParams struct {
	ID           int64       `json:"id"`
	Status       string      `json:"status"`
	IndexedAt    pgtype.Int8 `json:"indexed_at"`
	ErrorMessage pgtype.Text `json:"error_message"`
	Updated      int64       `json:"updated"`
}

func (q *Queries) UpdateRepoStatus(ctx context.Context, arg UpdateRepoStatusParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepoStatus,
		arg.ID,
		arg.Status,
		arg.IndexedAt,
		arg.ErrorMessage,
		arg.Updated,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GitTokenID,
		&i.Url,
		&i.Branch,
		&i.IsPrivate,
		&i.Status,
		&i.IndexedAt,
		&i.ErrorMessage,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
