// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings
WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT key, value, is_secret, updated
FROM settings
WHERE key = $1
`

func (q *Queries) GetSettingByKey(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingByKey, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.Updated,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, is_secret, updated
FROM settings
ORDER BY key ASC
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO settings (key, value, is_secret, updated)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
  SET value     = EXCLUDED.value,
      is_secret = EXCLUDED.is_secret,
      updated   = EXCLUDED.updated
RETURNING key, value, is_secret, updated
`

type UpsertSettingParams struct {
	Key      string `json:"key"`
	Value    []byte `json:"value"`
	IsSecret bool   `json:"is_secret"`
	Updated  int64  `json:"updated"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertSetting,
		arg.Key,
		arg.Value,
		arg.IsSecret,
		arg.Updated,
	)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.Updated,
	)
	return i, err
}
